<?php
include_once("../config/dataHandler_Coupons.php");

class CouponsManager {
    private $dh;

    function __construct() {
        $this->dh = new DataHandler_Coupons();
    }

    public function getCoupons() {
        $result = $this->dh->queryAllCoupons();
        
        if ($result) {
            return array(
                'status' => 'success',
                'message' => 'Coupons data retrieved successfully',
                'data' => $result
            );
        } else {
            return array(
                'status' => 'error',
                'message' => 'Error retrieving coupons data'
            );
        }
    }

    public function createCoupon($couponData) {
        $newCoupon = new Coupon(
            null, //ID is auto-generated by the db
            $couponData['code'],
            $couponData['discountAmount'],
            $couponData['discountType'],
            $couponData['expirationDate']
        );

        $result = $this->dh->createCoupon($newCoupon);
    
        if ($result) {
            return array(
                'status' => 'success',
                'message' => 'Coupon created successfully'
            );
        } else {
            return array(
                'status' => 'error',
                'message' => 'Error creating coupon'
            );
        }
    }

    public function checkCouponValidity($couponId) {
        $couponDetails = $this->dh->queryCouponById($couponId);
        
        if ($couponDetails) {
            $currentDate = new DateTime(); // Current date
            $expirationDate = new DateTime($couponDetails['expirationDate']); // Expiration date from the database
            
            if ($expirationDate >= $currentDate) {
                return array("status" => "success", "isValid" => true);
            } else {
                return array("status" => "success", "isValid" => false, "message" => "Coupon expired");
            }
        } else {
            return array("status" => "error", "isValid" => false, "message" => "Coupon not found");
        }
    }
}