<?php
include_once("../config/dataHandler_Coupons.php");

class CouponsManager {
    private $dh;

    function __construct() {
        $this->dh = new DataHandler_Coupons();
    }

    public function getCoupons() {
        $result = $this->dh->queryAllCoupons();
        
        if ($result) {
            return array(
                'status' => 'success',
                'message' => 'Coupons data retrieved successfully',
                'data' => $result
            );
        } else {
            return array(
                'status' => 'error',
                'message' => 'Error retrieving coupons data'
            );
        }
    }

    public function createCoupon($couponData) {
        $newCoupon = new Coupon(
            null, //ID is auto-generated by the db
            $couponData['code'],
            $couponData['discountAmount'],
            $couponData['discountType'],
            $couponData['expirationDate']
        );

        $result = $this->dh->createCoupon($newCoupon);
    
        if ($result) {
            return array(
                'status' => 'success',
                'message' => 'Coupon created successfully'
            );
        } else {
            return array(
                'status' => 'error',
                'message' => 'Error creating coupon'
            );
        }
    }

    public function checkCouponValidity($couponId) {
        $couponDetails = $this->dh->queryCouponById($couponId);
        
        if ($couponDetails) {
            $currentDate = new DateTime(); // Current date
            $expirationDate = new DateTime($couponDetails['expirationDate']); // Expiration date from the database
            
            if ($expirationDate >= $currentDate) {
                return array("status" => "success", "isValid" => true);
            } else {
                return array("status" => "success", "isValid" => false, "message" => "Coupon expired");
            }
        } else {
            return array("status" => "error", "isValid" => false, "message" => "Coupon not found");
        }
    }

    public function verifyVoucherCode($param) {
        $voucherCode = $param['voucherCode'];
        error_log("Received voucher code in CouponsManager: " . $voucherCode);  // Debugging
        $voucherDetails = $this->dh->queryCouponByCode($voucherCode);
        error_log("Result from DataHandler: " . json_encode($voucherDetails));  // Debugging
    
        if ($voucherDetails) {
            // Convert the expirationDate from the database to a DateTime object
            $expirationDate = new DateTime($voucherDetails['expirationDate']);
            $today = new DateTime(); // Today's date
    
            // Check if the expiration date is before today
            if ($expirationDate < $today) {
                return array("status" => "error", "message" => "Voucher expired");
            }
    
            return array(
                "status" => "success", 
                "discountAmount" => $voucherDetails['discountAmount'], 
                "discountType" => $voucherDetails['discountType'],
                "expirationDate" => $voucherDetails['expirationDate']
            );
        } else {
            return array("status" => "error", "message" => "Voucher not found");
        }
    }
}